language: python
python:
  - "3.6"

services:
  - docker

script:
  - "pytest"
  - docker build -t test:latest .
  - docker run --rm test:latest add 2 -2
  - docker run --rm test:latest sub 2 2
  - docker run --rm test:latest mul 2 0
  - docker run --rm test:latest div 0 10


